### ISSUE TITLE
Make it work with local ESLint

### ISSUE THREAD

**Issue by mqklin** [nemoxps/eslint-plugin-nemoxps#1]
First of all, thank you for the plugin, but sadly I can't use it now.
After run, this error is appearing: `Error while running ESLint: Cannot find module '../../eslint/node_modules/lodash'`
I have `eslint` in my `devDependencies`
Relative thread: https://github.com/eslint/eslint/issues/8230

**Comment by nemoxps** [comment]
@mqklin I hope it will work for you, now.

**Comment by mqklin** [comment]
It works except rule for a constructor:
![image](https://user-images.githubusercontent.com/9456433/32265233-0363f9c0-bf04-11e7-9afe-ebe0f9657efc.png)

How can I fix this?
Thank you.

**Comment by mqklin** [comment]
Also doesn't work for this case:
![image](https://user-images.githubusercontent.com/9456433/32265907-f561b3e6-bf06-11e7-967a-f77f98d1912b.png)

My eslintrc:
```
    'indent': 0,
    'nemoxps/indent': [2, 2, {
      'SwitchCase': 1,
      'ClassDeclaration': 2,
      'ClassExpression': 2,
    }],

```

**Comment by nemoxps** [comment]
Umm... With your configuration from above, those errors seem correct. 2 spaces default indentation and twice (4 spaces) in classes.
The class field in your first pic slips through because it's not part of the language, yet.

```js
const KNOWN_NODES = new Set([
    ...
]);
```

```js
'*:exit'(node) {
    // If a node's type is nonstandard, we can't tell how its children should be offset, so ignore it.
    if (!KNOWN_NODES.has(node.type))
      ignoredNodes.add(node);
},
```
